version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "local-test-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-w95gup5y064e"
s3_prefix = "local-test-app"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
